spring:
  application:
    name: API-GATEWAY

server:
  port: 8081

eureka:
  client:
    service-url:
      default-ze: ${EUREKA_URI:http://localhost:8761}
  instance:
    prefer-ip-addreass: true

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    account-service:
      path: /ticket/**
      serviceId: TICKET-SERVICE
    custumer-service:
      path: /produto/**
      serviceId: PRODUTO-SERVICE
  host:
    socket-timeout-millis: 30000